(deftheme terminal-pro
  "Theme for terminal ``pro'' profile")

(custom-theme-set-faces
 'terminal-pro
 '(default ((t (:inherit nil :extend nil :stipple nil :background "unspecified-bg" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(company-scrollbar-bg ((t (:background "color-242"))))
 '(company-scrollbar-fg ((t (:background "color-240"))))
 '(company-tooltip ((t (:background "color-244"))))
 '(company-tooltip-annotation ((t (:foreground "color-83"))))
 '(company-tooltip-common ((t (:foreground "brightwhite" :slant italic :weight bold))))
 '(company-tooltip-selection ((t (:background "color-242" :weight bold))))
 '(error ((t (:foreground "color-28" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "color-76"))))
 '(font-lock-comment-face ((t (:foreground "cyan" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "brightblue"))))
 '(font-lock-function-name-face ((t (:foreground "color-27"))))
 '(font-lock-keyword-face ((t (:foreground "yellow" :weight semi-bold))))
 '(font-lock-string-face ((t (:foreground "color-78"))))
 '(hi-green ((t (:background "color-30" :foreground "black"))))
 '(hi-pink ((t (:background "color-24" :foreground "black"))))
 '(hi-yellow ((t (:background "cyan" :foreground "black"))))
 '(highlight ((t (:background "color-234"))))
 '(isearch-fail ((t (:background "color-125"))))
 '(ivy-current-match ((t (:extend t :background "#1a4b77" :foreground "white" :weight bold))))
 '(ivy-minibuffer-match-face-1 ((t (:background "color-28"))))
 '(ivy-minibuffer-match-face-2 ((t (:background "color-29" :weight bold))))
 '(ivy-minibuffer-match-face-3 ((t (:background "color-30" :weight bold))))
 '(ivy-minibuffer-match-face-4 ((t (:background "color-31" :weight bold))))
 '(lazy-highlight ((t (:background "red"))))
 '(lsp-lsp-flycheck-warning-unnecessary-face ((t (:inherit warning :underline t))) t)
 '(lsp-ui-doc-background ((t (:background "color-242"))))
 '(lsp-ui-doc-header ((t (:background "color-240" :foreground "black"))))
 '(magit-section-highlight ((t (:extend t :background "color-239"))))
 '(match ((t (:background "color-102"))))
 '(minibuffer-prompt ((t (:foreground "color-171"))))
 '(mode-line ((t (:background "color-236" :box (:line-width -1 :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "color-236" :foreground "brightcyan" :box (:line-width -1 :color "grey75") :weight light))))
 '(popup-tip-face ((t (:background "color-238"))))
 '(region ((t (:extend t :background "color-237"))))
 '(show-paren-match ((t (:underline "brightyellow" :weight bold))))
 '(warning ((t (:foreground "color-22" :weight bold))))
 '(web-mode-html-tag-bracket-face ((t (:foreground "color-28")))))

(provide-theme 'terminal-pro)
